### Site Settings ###
title               : Faye Zhang
description         : >-
                      Nice to meet you~ (^-^)/<br>
                      I am a 3x <a href="https://www.google.com/">Google</a> SWE Intern,
                      <a href="https://fiverings.com/">Five Rings</a> SDE Intern,
                      Interactive CG Intern @ <a href="https://www.teamlab.art/">teamlab</a>,
                      and a Computer Science + Design student :book: @ <a href="https://www.upenn.edu">UPenn</a>.
baseurl             : ""
repository          : fayefzhang/fayefzhang.github.io
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : false


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Faye Zhang
  image             : assets/faye_zhang.jpg
# behance           : your_username
# dribbble          : your_username
  email             : ffz@seas.upenn.edu
# facebook          : your_username
  github            : fayefzhang
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : fayefzhang
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Collections ###
collections:
  projects:
    output: true
    permalink: /work/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "work"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
